
### To load using installed version and data/mscoco_label_map.pbtxt
### You may also need to download protoc for your platform

# Coco Category Index
# - from visualization_utils.py in utils
# - category_index: a dict containing category dictionaries (each holding
# - category index `id` and category name `name`) keyed by category indices.
# "Here we use internal utility functions, but anything that returns
# a dictionary mapping integers to appropriate string labels would be fine"

# MSCOCO to category index - debug inference
# Added "NOT USED" 12, 26, 29, 30, 45, 66, 68, 69, 71, 83
category_index_inference_debug_only = {
    1:{'name': "person"}, 
    2:{'name': "bicycle"}, 
    3:{'name': "car"}, 
    4:{'name': "motorcycle"}, 
    5:{'name': "airplane"}, 
    6:{'name': "bus"}, 
    7:{'name': "train"}, 
    8:{'name': "truck"}, 
    9:{'name': "boat"}, 
    10:{'name': "traffic light"}, 
    11:{'name': "fire hydrant"},
    12:{'name': "NOT USED"}, 
    13:{'name': "stop sign"}, 
    14:{'name': "parking meter"}, 
    15:{'name': "bench"}, 
    16:{'name': "bird"}, 
    17:{'name': "cat"}, 
    18:{'name': "dog"}, 
    19:{'name': "horse"}, 
    20:{'name': "sheep"}, 
    21:{'name': "cow"}, 
    22:{'name': "elephant"}, 
    23:{'name': "bear"}, 
    24:{'name': "zebra"}, 
    25:{'name': "giraffe"},
    26:{'name': "NOT USED"}, 
    27:{'name': "backpack"}, 
    28:{'name': "umbrella"},
    29:{'name': "NOT USED"},
    30:{'name': "NOT USED"}, 
    31:{'name': "handbag"}, 
    32:{'name': "tie"}, 
    33:{'name': "suitcase"}, 
    34:{'name': "frisbee"}, 
    35:{'name': "skis"}, 
    36:{'name': "snowboard"}, 
    37:{'name': "sports ball"}, 
    38:{'name': "kite"}, 
    39:{'name': "baseball bat"}, 
    40:{'name': "baseball glove"}, 
    41:{'name': "skateboard"}, 
    42:{'name': "surfboard"}, 
    43:{'name': "tennis racket"}, 
    44:{'name': "bottle"},
    45:{'name': "NOT USED"}, 
    46:{'name': "wine glass"}, 
    47:{'name': "cup"}, 
    48:{'name': "fork"}, 
    49:{'name': "knife"}, 
    50:{'name': "spoon"}, 
    51:{'name': "bowl"}, 
    52:{'name': "banana"}, 
    53:{'name': "apple"}, 
    54:{'name': "sandwich"}, 
    55:{'name': "orange"}, 
    56:{'name': "broccoli"}, 
    57:{'name': "carrot"}, 
    58:{'name': "hot dog"}, 
    59:{'name': "pizza"}, 
    60:{'name': "donut"}, 
    61:{'name': "cake"}, 
    62:{'name': "chair"}, 
    63:{'name': "couch"}, 
    64:{'name': "potted plant"}, 
    65:{'name': "bed"},
    66:{'name': "NOT USED"}, 
    67:{'name': "dining table"},
    68:{'name': "NOT USED"}, 
    69:{'name': "NOT USED"}, 
    70:{'name': "toilet"},
    71:{'name': "NOT USED"}, 
    72:{'name': "tv"},
    73:{'name': "laptop"}, 
    74:{'name': "mouse"}, 
    75:{'name': "remote"}, 
    76:{'name': "keyboard"}, 
    77:{'name': "cell phone"}, 
    78:{'name': "microwave"}, 
    79:{'name': "oven"}, 
    80:{'name': "toaster"}, 
    81:{'name': "sink"}, 
    82:{'name': "refrigerator"},
    83:{'name': "NOT USED"}, 
    84:{'name': "book"}, 
    85:{'name': "clock"}, 
    86:{'name': "vase"}, 
    87:{'name': "scissors"}, 
    88:{'name': "teddy bear"}, 
    89:{'name': "hair drier"}, 
    90:{'name': "toothbrush"}}

# Raw output from using tf labelmap util mscoco_label_map.txt
# ref from object_detection.utils import label_map_util
# ref label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
# ref categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
# ref category_index = label_map_util.create_category_index(categories)
mscoco_category_index = {
    1: {'id': 1, 'name': 'person'},
    2: {'id': 2, 'name': 'bicycle'},
    3: {'id': 3, 'name': 'car'},
    4: {'id': 4, 'name': 'motorcycle'},
    5: {'id': 5, 'name': 'airplane'},
    6: {'id': 6, 'name': 'bus'},
    7: {'id': 7, 'name': 'train'},
    8: {'id': 8, 'name': 'truck'},
    9: {'id': 9, 'name': 'boat'},
    10: {'id': 10, 'name': 'traffic light'},
    11: {'id': 11, 'name': 'fire hydrant'},
    13: {'id': 13, 'name': 'stop sign'},
    14: {'id': 14, 'name': 'parking meter'},
    15: {'id': 15, 'name': 'bench'},
    16: {'id': 16, 'name': 'bird'},
    17: {'id': 17, 'name': 'cat'},
    18: {'id': 18, 'name': 'dog'},
    19: {'id': 19, 'name': 'horse'},
    20: {'id': 20, 'name': 'sheep'},
    21: {'id': 21, 'name': 'cow'},
    22: {'id': 22, 'name': 'elephant'},
    23: {'id': 23, 'name': 'bear'},
    24: {'id': 24, 'name': 'zebra'},
    25: {'id': 25, 'name': 'giraffe'},
    27: {'id': 27, 'name': 'backpack'},
    28: {'id': 28, 'name': 'umbrella'},
    31: {'id': 31, 'name': 'handbag'},
    32: {'id': 32, 'name': 'tie'},
    33: {'id': 33, 'name': 'suitcase'},
    34: {'id': 34, 'name': 'frisbee'},
    35: {'id': 35, 'name': 'skis'},
    36: {'id': 36, 'name': 'snowboard'},
    37: {'id': 37, 'name': 'sports ball'},
    38: {'id': 38, 'name': 'kite'},
    39: {'id': 39, 'name': 'baseball bat'},
    40: {'id': 40, 'name': 'baseball glove'},
    41: {'id': 41, 'name': 'skateboard'},
    42: {'id': 42, 'name': 'surfboard'},
    43: {'id': 43, 'name': 'tennis racket'},
    44: {'id': 44, 'name': 'bottle'},
    46: {'id': 46, 'name': 'wine glass'},
    47: {'id': 47, 'name': 'cup'},
    48: {'id': 48, 'name': 'fork'},
    49: {'id': 49, 'name': 'knife'},
    50: {'id': 50, 'name': 'spoon'},
    51: {'id': 51, 'name': 'bowl'},
    52: {'id': 52, 'name': 'banana'},
    53: {'id': 53, 'name': 'apple'},
    54: {'id': 54, 'name': 'sandwich'},
    55: {'id': 55, 'name': 'orange'},
    56: {'id': 56, 'name': 'broccoli'},
    57: {'id': 57, 'name': 'carrot'},
    58: {'id': 58, 'name': 'hot dog'},
    59: {'id': 59, 'name': 'pizza'},
    60: {'id': 60, 'name': 'donut'},
    61: {'id': 61, 'name': 'cake'},
    62: {'id': 62, 'name': 'chair'},
    63: {'id': 63, 'name': 'couch'},
    64: {'id': 64, 'name': 'potted plant'},
    65: {'id': 65, 'name': 'bed'},
    67: {'id': 67, 'name': 'dining table'},
    70: {'id': 70, 'name': 'toilet'},
    72: {'id': 72, 'name': 'tv'},
    73: {'id': 73, 'name': 'laptop'},
    74: {'id': 74, 'name': 'mouse'},
    75: {'id': 75, 'name': 'remote'},
    76: {'id': 76, 'name': 'keyboard'},
    77: {'id': 77, 'name': 'cell phone'},
    78: {'id': 78, 'name': 'microwave'},
    79: {'id': 79, 'name': 'oven'},
    80: {'id': 80, 'name': 'toaster'},
    81: {'id': 81, 'name': 'sink'},
    82: {'id': 82, 'name': 'refrigerator'},
    84: {'id': 84, 'name': 'book'},
    85: {'id': 85, 'name': 'clock'},
    86: {'id': 86, 'name': 'vase'},
    87: {'id': 87, 'name': 'scissors'},
    88: {'id': 88, 'name': 'teddy bear'},
    89: {'id': 89, 'name': 'hair drier'},
    90: {'id': 90, 'name': 'toothbrush'}}

# From json file in mscoco panoptic coco api
# Color is not used but could store a preferred color for a category
mscoco_panoptic_category_index = {
    1:{"supercategory": "person", "color": [220, 20, 60], "isthing": 1, "id": 1, "name": "person"}, 
    2:{"supercategory": "vehicle", "color": [119, 11, 32], "isthing": 1, "id": 2, "name": "bicycle"}, 
    3:{"supercategory": "vehicle", "color": [0, 0, 142], "isthing": 1, "id": 3, "name": "car"}, 
    4:{"supercategory": "vehicle", "color": [0, 0, 230], "isthing": 1, "id": 4, "name": "motorcycle"}, 
    5:{"supercategory": "vehicle", "color": [106, 0, 228], "isthing": 1, "id": 5, "name": "airplane"}, 
    6:{"supercategory": "vehicle", "color": [0, 60, 100], "isthing": 1, "id": 6, "name": "bus"}, 
    7:{"supercategory": "vehicle", "color": [0, 80, 100], "isthing": 1, "id": 7, "name": "train"}, 
    8:{"supercategory": "vehicle", "color": [0, 0, 70], "isthing": 1, "id": 8, "name": "truck"}, 
    9:{"supercategory": "vehicle", "color": [0, 0, 192], "isthing": 1, "id": 9, "name": "boat"}, 
    10:{"supercategory": "outdoor", "color": [250, 170, 30], "isthing": 1, "id": 10, "name": "traffic light"}, 
    11:{"supercategory": "outdoor", "color": [100, 170, 30], "isthing": 1, "id": 11, "name": "fire hydrant"}, 
    13:{"supercategory": "outdoor", "color": [220, 220, 0], "isthing": 1, "id": 13, "name": "stop sign"}, 
    14:{"supercategory": "outdoor", "color": [175, 116, 175], "isthing": 1, "id": 14, "name": "parking meter"}, 
    15:{"supercategory": "outdoor", "color": [250, 0, 30], "isthing": 1, "id": 15, "name": "bench"}, 
    16:{"supercategory": "animal", "color": [165, 42, 42], "isthing": 1, "id": 16, "name": "bird"}, 
    17:{"supercategory": "animal", "color": [255, 77, 255], "isthing": 1, "id": 17, "name": "cat"}, 
    18:{"supercategory": "animal", "color": [0, 226, 252], "isthing": 1, "id": 18, "name": "dog"}, 
    19:{"supercategory": "animal", "color": [182, 182, 255], "isthing": 1, "id": 19, "name": "horse"}, 
    20:{"supercategory": "animal", "color": [0, 82, 0], "isthing": 1, "id": 20, "name": "sheep"}, 
    21:{"supercategory": "animal", "color": [120, 166, 157], "isthing": 1, "id": 21, "name": "cow"}, 
    22:{"supercategory": "animal", "color": [110, 76, 0], "isthing": 1, "id": 22, "name": "elephant"}, 
    23:{"supercategory": "animal", "color": [174, 57, 255], "isthing": 1, "id": 23, "name": "bear"}, 
    24:{"supercategory": "animal", "color": [199, 100, 0], "isthing": 1, "id": 24, "name": "zebra"}, 
    25:{"supercategory": "animal", "color": [72, 0, 118], "isthing": 1, "id": 25, "name": "giraffe"}, 
    27:{"supercategory": "accessory", "color": [255, 179, 240], "isthing": 1, "id": 27, "name": "backpack"}, 
    28:{"supercategory": "accessory", "color": [0, 125, 92], "isthing": 1, "id": 28, "name": "umbrella"}, 
    31:{"supercategory": "accessory", "color": [209, 0, 151], "isthing": 1, "id": 31, "name": "handbag"}, 
    32:{"supercategory": "accessory", "color": [188, 208, 182], "isthing": 1, "id": 32, "name": "tie"}, 
    33:{"supercategory": "accessory", "color": [0, 220, 176], "isthing": 1, "id": 33, "name": "suitcase"}, 
    34:{"supercategory": "sports", "color": [255, 99, 164], "isthing": 1, "id": 34, "name": "frisbee"}, 
    35:{"supercategory": "sports", "color": [92, 0, 73], "isthing": 1, "id": 35, "name": "skis"}, 
    36:{"supercategory": "sports", "color": [133, 129, 255], "isthing": 1, "id": 36, "name": "snowboard"}, 
    37:{"supercategory": "sports", "color": [78, 180, 255], "isthing": 1, "id": 37, "name": "sports ball"}, 
    38:{"supercategory": "sports", "color": [0, 228, 0], "isthing": 1, "id": 38, "name": "kite"}, 
    39:{"supercategory": "sports", "color": [174, 255, 243], "isthing": 1, "id": 39, "name": "baseball bat"}, 
    40:{"supercategory": "sports", "color": [45, 89, 255], "isthing": 1, "id": 40, "name": "baseball glove"}, 
    41:{"supercategory": "sports", "color": [134, 134, 103], "isthing": 1, "id": 41, "name": "skateboard"}, 
    42:{"supercategory": "sports", "color": [145, 148, 174], "isthing": 1, "id": 42, "name": "surfboard"}, 
    43:{"supercategory": "sports", "color": [255, 208, 186], "isthing": 1, "id": 43, "name": "tennis racket"}, 
    44:{"supercategory": "kitchen", "color": [197, 226, 255], "isthing": 1, "id": 44, "name": "bottle"}, 
    46:{"supercategory": "kitchen", "color": [171, 134, 1], "isthing": 1, "id": 46, "name": "wine glass"}, 
    47:{"supercategory": "kitchen", "color": [109, 63, 54], "isthing": 1, "id": 47, "name": "cup"}, 
    48:{"supercategory": "kitchen", "color": [207, 138, 255], "isthing": 1, "id": 48, "name": "fork"}, 
    49:{"supercategory": "kitchen", "color": [151, 0, 95], "isthing": 1, "id": 49, "name": "knife"}, 
    50:{"supercategory": "kitchen", "color": [9, 80, 61], "isthing": 1, "id": 50, "name": "spoon"}, 
    51:{"supercategory": "kitchen", "color": [84, 105, 51], "isthing": 1, "id": 51, "name": "bowl"}, 
    52:{"supercategory": "food", "color": [74, 65, 105], "isthing": 1, "id": 52, "name": "banana"}, 
    53:{"supercategory": "food", "color": [166, 196, 102], "isthing": 1, "id": 53, "name": "apple"}, 
    54:{"supercategory": "food", "color": [208, 195, 210], "isthing": 1, "id": 54, "name": "sandwich"}, 
    55:{"supercategory": "food", "color": [255, 109, 65], "isthing": 1, "id": 55, "name": "orange"}, 
    56:{"supercategory": "food", "color": [0, 143, 149], "isthing": 1, "id": 56, "name": "broccoli"}, 
    57:{"supercategory": "food", "color": [179, 0, 194], "isthing": 1, "id": 57, "name": "carrot"}, 
    58:{"supercategory": "food", "color": [209, 99, 106], "isthing": 1, "id": 58, "name": "hot dog"}, 
    59:{"supercategory": "food", "color": [5, 121, 0], "isthing": 1, "id": 59, "name": "pizza"}, 
    60:{"supercategory": "food", "color": [227, 255, 205], "isthing": 1, "id": 60, "name": "donut"}, 
    61:{"supercategory": "food", "color": [147, 186, 208], "isthing": 1, "id": 61, "name": "cake"}, 
    62:{"supercategory": "furniture", "color": [153, 69, 1], "isthing": 1, "id": 62, "name": "chair"}, 
    63:{"supercategory": "furniture", "color": [3, 95, 161], "isthing": 1, "id": 63, "name": "couch"}, 
    64:{"supercategory": "furniture", "color": [163, 255, 0], "isthing": 1, "id": 64, "name": "potted plant"}, 
    65:{"supercategory": "furniture", "color": [119, 0, 170], "isthing": 1, "id": 65, "name": "bed"}, 
    67:{"supercategory": "furniture", "color": [0, 182, 199], "isthing": 1, "id": 67, "name": "dining table"}, 
    70:{"supercategory": "furniture", "color": [0, 165, 120], "isthing": 1, "id": 70, "name": "toilet"}, 
    72:{"supercategory": "electronic", "color": [183, 130, 88], "isthing": 1, "id": 72, "name": "tv"}, 
    73:{"supercategory": "electronic", "color": [95, 32, 0], "isthing": 1, "id": 73, "name": "laptop"}, 
    74:{"supercategory": "electronic", "color": [130, 114, 135], "isthing": 1, "id": 74, "name": "mouse"}, 
    75:{"supercategory": "electronic", "color": [110, 129, 133], "isthing": 1, "id": 75, "name": "remote"}, 
    76:{"supercategory": "electronic", "color": [166, 74, 118], "isthing": 1, "id": 76, "name": "keyboard"}, 
    77:{"supercategory": "electronic", "color": [219, 142, 185], "isthing": 1, "id": 77, "name": "cell phone"}, 
    78:{"supercategory": "appliance", "color": [79, 210, 114], "isthing": 1, "id": 78, "name": "microwave"}, 
    79:{"supercategory": "appliance", "color": [178, 90, 62], "isthing": 1, "id": 79, "name": "oven"}, 
    80:{"supercategory": "appliance", "color": [65, 70, 15], "isthing": 1, "id": 80, "name": "toaster"}, 
    81:{"supercategory": "appliance", "color": [127, 167, 115], "isthing": 1, "id": 81, "name": "sink"}, 
    82:{"supercategory": "appliance", "color": [59, 105, 106], "isthing": 1, "id": 82, "name": "refrigerator"}, 
    84:{"supercategory": "indoor", "color": [142, 108, 45], "isthing": 1, "id": 84, "name": "book"}, 
    85:{"supercategory": "indoor", "color": [196, 172, 0], "isthing": 1, "id": 85, "name": "clock"}, 
    86:{"supercategory": "indoor", "color": [95, 54, 80], "isthing": 1, "id": 86, "name": "vase"}, 
    87:{"supercategory": "indoor", "color": [128, 76, 255], "isthing": 1, "id": 87, "name": "scissors"}, 
    88:{"supercategory": "indoor", "color": [201, 57, 1], "isthing": 1, "id": 88, "name": "teddy bear"}, 
    89:{"supercategory": "indoor", "color": [246, 0, 122], "isthing": 1, "id": 89, "name": "hair drier"}, 
    90:{"supercategory": "indoor", "color": [191, 162, 208], "isthing": 1, "id": 90, "name": "toothbrush"}, 
    92:{"supercategory": "textile", "color": [255, 255, 128], "isthing": 0, "id": 92, "name": "banner"}, 
    93:{"supercategory": "textile", "color": [147, 211, 203], "isthing": 0, "id": 93, "name": "blanket"}, 
    94:{"supercategory": "building", "color": [150, 100, 100], "isthing": 0, "id": 95, "name": "bridge"}, 
    100:{"supercategory": "raw-material", "color": [168, 171, 172], "isthing": 0, "id": 100, "name": "cardboard"}, 
    107:{"supercategory": "furniture-stuff", "color": [146, 112, 198], "isthing": 0, "id": 107, "name": "counter"}, 
    109:{"supercategory": "textile", "color": [210, 170, 100], "isthing": 0, "id": 109, "name": "curtain"}, 
    112:{"supercategory": "furniture-stuff", "color": [92, 136, 89], "isthing": 0, "id": 112, "name": "door-stuff"}, 
    118:{"supercategory": "floor", "color": [218, 88, 184], "isthing": 0, "id": 118, "name": "floor-wood"}, 
    119:{"supercategory": "plant", "color": [241, 129, 0], "isthing": 0, "id": 119, "name": "flower"}, 
    122:{"supercategory": "food-stuff", "color": [217, 17, 255], "isthing": 0, "id": 122, "name": "fruit"}, 
    125:{"supercategory": "ground", "color": [124, 74, 181], "isthing": 0, "id": 125, "name": "gravel"}, 
    128:{"supercategory": "building", "color": [70, 70, 70], "isthing": 0, "id": 128, "name": "house"}, 
    130:{"supercategory": "furniture-stuff", "color": [255, 228, 255], "isthing": 0, "id": 130, "name": "light"}, 
    133:{"supercategory": "furniture-stuff", "color": [154, 208, 0], "isthing": 0, "id": 133, "name": "mirror-stuff"}, 
    138:{"supercategory": "structural", "color": [193, 0, 92], "isthing": 0, "id": 138, "name": "net"}, 
    141:{"supercategory": "textile", "color": [76, 91, 113], "isthing": 0, "id": 141, "name": "pillow"}, 
    144:{"supercategory": "ground", "color": [255, 180, 195], "isthing": 0, "id": 144, "name": "platform"}, 
    145:{"supercategory": "ground", "color": [106, 154, 176], "isthing": 0, "id": 145, "name": "playingfield"}, 
    147:{"supercategory": "ground", "color": [230, 150, 140], "isthing": 0, "id": 147, "name": "railroad"}, 
    148:{"supercategory": "water", "color": [60, 143, 255], "isthing": 0, "id": 148, "name": "river"}, 
    149:{"supercategory": "ground", "color": [128, 64, 128], "isthing": 0, "id": 149, "name": "road"}, 
    151:{"supercategory": "building", "color": [92, 82, 55], "isthing": 0, "id": 151, "name": "roof"}, 
    154:{"supercategory": "ground", "color": [254, 212, 124], "isthing": 0, "id": 154, "name": "sand"}, 
    155:{"supercategory": "water", "color": [73, 77, 174], "isthing": 0, "id": 155, "name": "sea"}, 
    156:{"supercategory": "furniture-stuff", "color": [255, 160, 98], "isthing": 0, "id": 156, "name": "shelf"}, 
    159:{"supercategory": "ground", "color": [255, 255, 255], "isthing": 0, "id": 159, "name": "snow"}, 
    161:{"supercategory": "furniture-stuff", "color": [104, 84, 109], "isthing": 0, "id": 161, "name": "stairs"}, 
    166:{"supercategory": "building", "color": [169, 164, 131], "isthing": 0, "id": 166, "name": "tent"}, 
    168:{"supercategory": "textile", "color": [225, 199, 255], "isthing": 0, "id": 168, "name": "towel"}, 
    171:{"supercategory": "wall", "color": [137, 54, 74], "isthing": 0, "id": 171, "name": "wall-brick"}, 
    175:{"supercategory": "wall", "color": [135, 158, 223], "isthing": 0, "id": 175, "name": "wall-stone"}, 
    176:{"supercategory": "wall", "color": [7, 246, 231], "isthing": 0, "id": 176, "name": "wall-tile"}, 
    177:{"supercategory": "wall", "color": [107, 255, 200], "isthing": 0, "id": 177, "name": "wall-wood"}, 
    178:{"supercategory": "water", "color": [58, 41, 149], "isthing": 0, "id": 178, "name": "water-other"}, 
    180:{"supercategory": "window", "color": [183, 121, 142], "isthing": 0, "id": 180, "name": "window-blind"}, 
    181:{"supercategory": "window", "color": [255, 73, 97], "isthing": 0, "id": 181, "name": "window-other"}, 
    184:{"supercategory": "plant", "color": [107, 142, 35], "isthing": 0, "id": 184, "name": "tree-merged"}, 
    185:{"supercategory": "structural", "color": [190, 153, 153], "isthing": 0, "id": 185, "name": "fence-merged"}, 
    186:{"supercategory": "ceiling", "color": [146, 139, 141], "isthing": 0, "id": 186, "name": "ceiling-merged"}, 
    187:{"supercategory": "sky", "color": [70, 130, 180], "isthing": 0, "id": 187, "name": "sky-other-merged"}, 
    188:{"supercategory": "furniture-stuff", "color": [134, 199, 156], "isthing": 0, "id": 188, "name": "cabinet-merged"}, 
    189:{"supercategory": "furniture-stuff", "color": [209, 226, 140], "isthing": 0, "id": 189, "name": "table-merged"}, 
    190:{"supercategory": "floor", "color": [96, 36, 108], "isthing": 0, "id": 190, "name": "floor-other-merged"}, 
    191:{"supercategory": "ground", "color": [96, 96, 96], "isthing": 0, "id": 191, "name": "pavement-merged"}, 
    192:{"supercategory": "solid", "color": [64, 170, 64], "isthing": 0, "id": 192, "name": "mountain-merged"}, 
    193:{"supercategory": "plant", "color": [152, 251, 152], "isthing": 0, "id": 193, "name": "grass-merged"}, 
    194:{"supercategory": "ground", "color": [208, 229, 228], "isthing": 0, "id": 194, "name": "dirt-merged"}, 
    195:{"supercategory": "raw-material", "color": [206, 186, 171], "isthing": 0, "id": 195, "name": "paper-merged"}, 
    196:{"supercategory": "food-stuff", "color": [152, 161, 64], "isthing": 0, "id": 196, "name": "food-other-merged"}, 
    197:{"supercategory": "building", "color": [116, 112, 0], "isthing": 0, "id": 197, "name": "building-other-merged"}, 
    198:{"supercategory": "solid", "color": [0, 114, 143], "isthing": 0, "id": 198, "name": "rock-merged"}, 
    199:{"supercategory": "wall", "color": [102, 102, 156], "isthing": 0, "id": 199, "name": "wall-other-merged"}, 
    200:{"supercategory": "textile", "color": [250, 141, 255], "isthing": 0, "id": 200, "name": "rug-merged"}}

# My preferred category index
# COCO (90 id) (80 count) 'Things' / Objects
# Added display_name.  Only effects visual image (if display_name else name)
# International/Context Spelling or Capitalize (ise)
# tennis racket to Racket - also include correctly squash and badmiton???
# sports ball loses nothing as also no other balls
# baseball bat (and glove) correctly with softball, chance of cricket etc
# wine glass to Glass is gray (grey) area as it losses descriptor
# traffic light, stop sign, parking meter would need to be kept long
# Most of the time having 'unlikely' things are good to check confidence
# Other times it can be bad. eg when farm animals turn up domestically
# - or exotic animals turn up anywhere but in a zoo.
# Can also correct id with general name eg below # or Animal
# This is just for the visual but can be helpful for untrained people
# - keeps reporting cats as cows or dogs as bears etc
# - you can hide the false positive in visual but count for stats/training
# - Quicker / simpler solution than retraining
my_coco_category_index = {
    1: {'id': 1, 'name': 'person', 'display_name': 'Person'},
    2: {'id': 2, 'name': 'bicycle', 'display_name': 'Bike'},
    3: {'id': 3, 'name': 'car', 'display_name': 'Car'},
    4: {'id': 4, 'name': 'motorcycle', 'display_name': 'Motorbike'},
    5: {'id': 5, 'name': 'airplane', 'display_name': 'Plane'},
    6: {'id': 6, 'name': 'bus', 'display_name': 'Bus'},
    7: {'id': 7, 'name': 'train', 'display_name': 'Train'},
    8: {'id': 8, 'name': 'truck', 'display_name': 'Truck'},
    9: {'id': 9, 'name': 'boat', 'display_name': 'Boat'},
    10: {'id': 10, 'name': 'traffic light', 'display_name': 'Traffic Light'},
    11: {'id': 11, 'name': 'fire hydrant', 'display_name': 'Fire Hydrant'},
    13: {'id': 13, 'name': 'stop sign', 'display_name': 'Stop Sign'},
    14: {'id': 14, 'name': 'parking meter', 'display_name': 'Parking Meter'},
    15: {'id': 15, 'name': 'bench', 'display_name': 'Bench'},
    16: {'id': 16, 'name': 'bird', 'display_name': 'Bird'},
    17: {'id': 17, 'name': 'cat', 'display_name': 'Cat'},
    18: {'id': 18, 'name': 'dog', 'display_name': 'Dog'},
    19: {'id': 19, 'name': 'horse', 'display_name': 'Horse'},
    20: {'id': 20, 'name': 'sheep', 'display_name': 'Sheep'},
    21: {'id': 21, 'name': 'cow', 'display_name': 'Cow'},
    22: {'id': 22, 'name': 'elephant', 'display_name': 'Elephant'}, 
    23: {'id': 23, 'name': 'bear', 'display_name': 'Bear'}, 
    24: {'id': 24, 'name': 'zebra', 'display_name': 'Zebra'}, 
    25: {'id': 25, 'name': 'giraffe', 'display_name': 'Giraffe'}, 
    27: {'id': 27, 'name': 'backpack', 'display_name': 'Backpack'},
    28: {'id': 28, 'name': 'umbrella', 'display_name': 'Umbrella'},
    31: {'id': 31, 'name': 'handbag', 'display_name': 'Handbag'},
    32: {'id': 32, 'name': 'tie', 'display_name': 'Tie'},
    33: {'id': 33, 'name': 'suitcase', 'display_name': 'Suitcase'},
    34: {'id': 34, 'name': 'frisbee', 'display_name': 'Frisbee'},
    35: {'id': 35, 'name': 'skis', 'display_name': 'Skis'},
    36: {'id': 36, 'name': 'snowboard', 'display_name': 'Snowboard'},
    37: {'id': 37, 'name': 'sports ball', 'display_name': 'Ball'},
    38: {'id': 38, 'name': 'kite', 'display_name': 'Kite'},
    39: {'id': 39, 'name': 'baseball bat', 'display_name': 'Bat'},
    40: {'id': 40, 'name': 'baseball glove', 'display_name': 'Glove'},
    41: {'id': 41, 'name': 'skateboard', 'display_name': 'Skateboard'},
    42: {'id': 42, 'name': 'surfboard', 'display_name': 'Surfboard'},
    43: {'id': 43, 'name': 'tennis racket', 'display_name': 'Racket'},
    44: {'id': 44, 'name': 'bottle', 'display_name': 'Bottle'},
    46: {'id': 46, 'name': 'wine glass', 'display_name': 'Glass'},
    47: {'id': 47, 'name': 'cup', 'display_name': 'Cup'},
    48: {'id': 48, 'name': 'fork', 'display_name': 'Fork'},
    49: {'id': 49, 'name': 'knife', 'display_name': 'Knife'},
    50: {'id': 50, 'name': 'spoon', 'display_name': 'Spoon'},
    51: {'id': 51, 'name': 'bowl', 'display_name': 'Bowl'},
    52: {'id': 52, 'name': 'banana', 'display_name': 'Banana'},
    53: {'id': 53, 'name': 'apple', 'display_name': 'Apple'},
    54: {'id': 54, 'name': 'sandwich', 'display_name': 'Sandwich'},
    55: {'id': 55, 'name': 'orange', 'display_name': 'Orange'},
    56: {'id': 56, 'name': 'broccoli', 'display_name': 'Broccoli'},
    57: {'id': 57, 'name': 'carrot', 'display_name': 'Carrot'},
    58: {'id': 58, 'name': 'hot dog', 'display_name': 'Hotdog'},
    59: {'id': 59, 'name': 'pizza', 'display_name': 'Pizza'},
    60: {'id': 60, 'name': 'donut', 'display_name': 'Donut'},
    61: {'id': 61, 'name': 'cake', 'display_name': 'Cake'},
    62: {'id': 62, 'name': 'chair', 'display_name': 'Chair'},
    63: {'id': 63, 'name': 'couch', 'display_name': 'Couch'},
    64: {'id': 64, 'name': 'potted plant', 'display_name': 'Plant'},
    65: {'id': 65, 'name': 'bed', 'display_name': 'Bed'},
    67: {'id': 67, 'name': 'dining table', 'display_name': 'Table'},
    70: {'id': 70, 'name': 'toilet', 'display_name': 'Toilet'},
    72: {'id': 72, 'name': 'tv', 'display_name': 'TV'},
    73: {'id': 73, 'name': 'laptop', 'display_name': 'Laptop'},
    74: {'id': 74, 'name': 'mouse', 'display_name': 'Mouse'},
    75: {'id': 75, 'name': 'remote', 'display_name': 'Remote'},
    76: {'id': 76, 'name': 'keyboard', 'display_name': 'Keyboard'},
    77: {'id': 77, 'name': 'cell phone', 'display_name': 'Phone'},
    78: {'id': 78, 'name': 'microwave', 'display_name': 'Microwave'},
    79: {'id': 79, 'name': 'oven', 'display_name': 'Oven'},
    80: {'id': 80, 'name': 'toaster', 'display_name': 'Toaster'},
    81: {'id': 81, 'name': 'sink', 'display_name': 'Sink'},
    82: {'id': 82, 'name': 'refrigerator', 'display_name': 'Fridge'},
    84: {'id': 84, 'name': 'book', 'display_name': 'Book'},
    85: {'id': 85, 'name': 'clock', 'display_name': 'Clock'},
    86: {'id': 86, 'name': 'vase', 'display_name': 'Vase'},
    87: {'id': 87, 'name': 'scissors', 'display_name': 'Scissors'},
    88: {'id': 88, 'name': 'teddy bear', 'display_name': 'Teddy Bear'},
    89: {'id': 89, 'name': 'hair drier', 'display_name': 'Hair Drier'},
    90: {'id': 90, 'name': 'toothbrush', 'display_name': 'Toothbrush'}}

